-- local builtin = require("telescope.builtin")
--
-- vim.keymap.set("n", "<leader>pb", builtin.buffers, {})
-- vim.keymap.set("n", "<leader>pf", builtin.find_files, {})
-- vim.keymap.set("n", "<C-p>", builtin.git_files, {})
-- vim.keymap.set("n", "<leader>ps", function()
-- 	builtin.grep_string({ search = vim.fn.input("Grep > ") })
-- end)
-- vim.keymap.set("n", "<leader>vh", builtin.help_tags, {})
--
-- require("telescope").setup({
-- 	defaults = {
-- 		prompt_prefix = " >",
-- 		color_devicons = true,
-- 		file_previewer = require("telescope.previewers").vim_buffer_cat.new,
-- 		grep_previewer = require("telescope.previewers").vim_buffer_vimgrep.new,
-- 		qflist_previewer = require("telescope.previewers").vim_buffer_qflist.new,
-- 	},
-- })
